name: Code Coverage
 
on:
  push:
    branches: [ feature/ENGA3-357-code-coverage ]
  pull_request:
  
jobs:
  coverage:
      name: Code-Coverage

      runs-on: ubuntu-latest

      strategy:
        fail-fast: false
        matrix:
          php-version:
            - "8.1"

      steps:
        - name: Checkout
          uses: actions/checkout@v2
          with:
            fetch-depth: 0
          
        - name: Setup PHP with Xdebug
          uses: shivammathur/setup-php@v2
          with:
            php-version: ${{ matrix.php-version }}
            coverage: xdebug
            
        - name: Install dependencies with composer
          run: composer update --no-ansi --no-interaction --no-progress
          
        - name: Run tests with phpunit/phpunit
          run: vendor/bin/phpunit --coverage-clover=coverage.xml
          
        - name: Fix code coverage paths
          run: sed -i 's@'$GITHUB_WORKSPACE'@/github/workspace/@g' coverage.xml
          
        - name: SonarCloud Scan
          uses: SonarSource/sonarcloud-github-action@master
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            SONAR_TOKEN: ${{ secrets.SONARCLOUD_TOKEN }}